language: java
jdk:
  - oraclejdk8
services:
  - postgresql
install: true
before_script:
  - psql -d template1 -c "create database engine_dao_tests owner postgres;" -U postgres
  - sudo rm -rf /etc/securetty # Work around ServletUtilsTest test
script:
  - "./packaging/dbscripts/schema.sh -d engine_dao_tests -u postgres -c apply"
  - mvn --quiet clean org.jacoco:jacoco-maven-plugin:prepare-agent install -P enable-dao-tests sonar:sonar -Dsonar.host.url=https://nemo.sonarqube.org -Dsonar.login=$SONAR_TOKEN -Dengine.db.username=postgres -Dengine.db.password
env:
  global:
    secure: kgBwT3IHk1vg1PHD4KKqkIOFlv4MGkOA+IK+nsTbPRJEvWpzZSgpHLuL+/2YuB4tntNMMj3LHwPTSJmaGLRdxaSjjv0MfzQA/fudLqTJ+FL3MuA++YcLSfjj6wj1dlMRj+0vYgCQcBMKTktDhGMdE6gUh42AQBzywqe1IcnX5Qs=
addons:
  postgresql: "9.2"
cache:
  directories:
    - $HOME/.m2
  before_cache:
    - rm -rf $HOME/.m2/repository/org/ovirt/
branches:
  only:
    - master
